Membertag/base
Gaship/gaship-shopping-mall pull request #10
Opened 2022-07-19 08:00 UTC by cofreeman

머지요청합니다..... 이건 머지

2022-07-19 15:02 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/member/entity/Member.java
> +    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL)
영속성 전이를 ALL로 해놓으신 이유가 있으실까요? 궁금해용

2022-07-19 15:04 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/controller/MemberTagController.java
> +     * @param memberTagRequestDto the member tag request dto
자바독 완성 부탁드립니다 ㅎㅎ

2022-07-19 15:05 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/controller/MemberTagController.java
> +        return ResponseEntity.status(HttpStatus.CREATED)
여기서의 CREATED는 새로운 태그의 생성이 아니라서 201은 어울리지않는거같아요.

2022-07-19 15:12 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/repository/MemberTagRepository.java
> +     * 회원이 기존에 설정한 모든 태그를 지우고 등록하길 원하는 모든 태그를 등록하는 메서드입니다.
doc을 작성할 때 팁하나를 드리자면

<i>회원이 기존에 설정한 모든 태그를 지우고 등록하길 원하는 모든 태그를 등록하는 메서드입니다.</i>
deleteAllByMember_MemberNo는 태그 전체 삭제하는 것이 그 역할이라면 해당 행위를 하는 항목만 작성하시는 편이 좋을 거 같습니다.

<i>"주석은 거짓말을 자주한다."</i> - clean code

저도 글재주, 주석 작성하는 능력이 현저히 떨어지지만, 가능한 진실만을 답하는 주석을 달도록 같이 노력해요.

2022-07-19 15:16 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/service/MemberTagServiceImpl.java
> +        IntStream.rangeClosed(0, 4).forEach(i -> memberTags.add(MemberTag.builder().member(member).tag(tagList.get(i)).build()));
```java
IntStream.rangeClosed(0, 4).forEach(i -> memberTags.add(MemberTag.builder().member(member).tag(tagList.get(i)).build()));
======
IntStream.rangeClosed(0, 4)
    .forEach(i -> memberTags.add(
        MemberTag.builder()
            .member(member)
            .tag(tagList.get(i))
            .build())
            );
```

체이닝 메서드가 발생하면 가로보단 세로가 읽기 편하실거에용

2022-07-19 15:22 UTC, oct-sky-out reviewed
주석부분을 내일 같이 채우러 갑시다! ㅎㅎ

2022-07-19 15:22 UTC, oct-sky-out requested changes
끝나면 Approve해드릴게요!

2022-07-20 00:33 UTC, cofreeman commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/service/MemberTagServiceImpl.java
> +        IntStream.rangeClosed(0, 4).forEach(i -> memberTags.add(MemberTag.builder().member(member).tag(tagList.get(i)).build()));
감사합니다 그게 더 보기 쉬운것 같네요 참고해서 수정하겠습니다

2022-07-20 00:56 UTC, cofreeman commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/controller/MemberTagController.java
> +        return ResponseEntity.status(HttpStatus.CREATED)
해당 메서드는 delete도 하지만 그것은 생성을 위한 삭제이고 해당 메서드의 사용자가 요청한 멤버 태그를 생성하는 것이기때문에 201로 해두었습니다

2022-07-20 00:57 UTC, cofreeman commented on src/main/java/shop/gaship/gashipshoppingmall/membertag/controller/MemberTagController.java
> +     * @param memberTagRequestDto the member tag request dto
네! 완성시키겠습니다

2022-07-20 01:33 UTC, merged