Feature/products
Gaship/gaship-shopping-mall pull request #21
Opened 2022-07-22 01:35 UTC by qnt012

2022-07-22 13:15 UTC, oct-sky-out requested changes
이미지 파일 resources에 들어간거도 지워주세요

2022-07-22 13:15 UTC, oct-sky-out commented on pom.xml
> +		</dependency>
이건 어떤 의존성인가요?

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/request/ProductCreateRequestDto.java
> +    private Integer deliveryTypeNo;
Min validation이 필요해보여요

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/request/ProductCreateRequestDto.java
> +    private String name;
String 객체를 Validation할 때는 NotNull이 포함된 NotBlank를 시용하셔야해요.

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/request/ProductCreateRequestDto.java
> +    private List<Integer> tagNos;
List의 size가 비어있으면 어떻게 되나요
또한 List와 같은 순열형 자료구조 또는 클래스 내부의 클래스형 필드값을 Validation할땐 어떻게 하는게 좋을까요...?

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/request/ProductRequestDto.java
> +@EqualsAndHashCode
롬복 equalsAndHashCode를 넣으신 특별한 이유를 알고싶어요

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/response/ProductAllInfoResponseDto.java
> +        this.upperName = upperName;
저는 이런 무수한 필드를 보면 볼 수록 builder패턴이 꼭 필요하다는 생각이들곤해요

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/repository/custom/ProductRepositoryCustom.java
> +public interface ProductRepositoryCustom {
커스텀 Repository는 NoRepositoryBean 어노테이션이 필요해요

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/repository/impl/ProductRepositoryImpl.java
> +                .fetchResults();
영롱하네요⭐️

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/repository/impl/ProductRepositoryImpl.java
> +        return new PageImpl<>(result.getResults(), requestDto.getPageable(), result.getTotal());
PageImpl도 좋지만 PageableExcutionUtil 클래스도 찾아보시길바라며...

https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/support/PageableExecutionUtils.html

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/ProductService.java
> +     * @throws StatusCodeNotFoundException 상태코드가 존재하지않을경우 발생합니다.
이러면 ProductService2라는 구현체가 생기면 해당 구현체까지 위 예외를 모두 던져야 문서가 거짓이되지않습니다. 따로 분리하는 것을 권장드려요☺️

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +                .orElseThrow(StatusCodeNotFoundException::new);
지금이 inherit을 사용하기 적절한 시기인거같습니다!

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/productTag/repository/impl/ProductTagRepositoryImpl.java
> +
Checkstyle 체킹해주새요!🙆🙆🙆

2022-07-22 13:15 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipshoppingmall/product/controller/ProductController.java
> +@RequestMapping("/products")
/api 작업도 겸해주시겠어요?

2022-07-24 05:25 UTC, SemiKimm commented on src/main/java/shop/gaship/gashipshoppingmall/product/repository/impl/ProductRepositoryImpl.java
> +                .fetchResults();
fetchResuls 가  querydsl 5.0 부터 deprecated 된다고 합니다. 
http://querydsl.com/static/querydsl/5.0.0/apidocs/deprecated-list.html
아래 민수님이 적어놓으신것처럼 PageableExcutionUtil 적용해보시면서 
하단 코드처럼 content 와 count 를 분리해서 적용해보는건 어떨까요

List<GradeHistoryResponseDto> content = from(gradeHistory)
                .where(gradeHistory.member.memberNo.eq(memberNo))
                .orderBy(gradeHistory.at.desc())
                .limit(pageRequest.getPageSize())
                .offset(pageRequest.getOffset())
                .select(Projections.bean(GradeHistoryResponseDto.class,
                        gradeHistory.at,
                        gradeHistory.totalAmount,
                        gradeHistory.gradeName))
                .fetch();

        return PageableExecutionUtils.getPage(content,
                pageRequest,
                () -> from(gradeHistory)
                        .where(gradeHistory.member.memberNo.eq(memberNo))
                        .fetch()
                        .size());

2022-07-25 01:09 UTC, qnt012 commented on pom.xml
> +		</dependency>
테스트를 위해 test 하위 resources에 이미지를 추가하였는데 지워야할까요?
commons.io는 파일 업로드를 위한 의존성으로 추가하였었는데 없어도 잘 돌아가네요. 지우도록 하겠습니다.

2022-07-25 01:28 UTC, HoFe-U commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/response/ProductAllInfoResponseDto.java
> +        this.upperName = upperName;
네 builder 추가했습니다.

2022-07-25 01:33 UTC, qnt012 commented on src/main/java/shop/gaship/gashipshoppingmall/product/dto/request/ProductCreateRequestDto.java
> +    private List<Integer> tagNos;
tagNos에 @NotEmpty를 추가하도록 하겠습니다.
내부값의 경우 List<@Valid> 처럼 작성하면 Validation이 가능하다고 하네요.

2022-07-25 03:29 UTC, nhn-academy-marco reviewed
고생하셨습니다.

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/repository/impl/ProductRepositoryImpl.java
> +        QCategory upper = new QCategory("upper");
QCategory upper = QCategory.qCategory 사용해보는건 어떨까요?

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        repository.save(product);
product가 save가 fail 상황에서 파일을 어떻게 처리를 해줘야 할지 고민해보면 좋을거 같아요.
반대로 파일업로드가 실패 했을 때 produt save되는 상황을 고민해보세요.

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        repository.save(product);
변경감지를 이용해보세요. //repository.save(product);

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        repository.save(product);
변경감지를 이용해보세요
//repository.save(product);

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        Page<ProductAllInfoResponseDto> products = repository.findProduct(requestDto);
중간에 ProductRequestDto로 만들어서 전달하는 이유가 있을까요? 
productCode, pageable 객체를 던저는게 가독성이 더 좋을거 같아요

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +            tag.forEach(t -> p.getTags().add(t.getTitle()));
p.getProductNo() 기준으로 foreach돌려서 N번 반복해서 테그 정보를 구하고 있는데요.
N번 방복하지말고 . 한방 쿼리로 처리 해보시는건 어떨가요? 예를들어  in (producntNo....) 형토로 변경해보면 어떨까요?

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        return new PageResponse<>(products);
PageResponse 객체의 위치가 service쪽에서 만들어서 반환해주는게 맞는거지 고민해보시면 좋을거 같아요.
서비스 단에서 PageResponse 반환을 하게되면 .. 다른 서비스에서 해당 서비스를 사용하려고 하면 PageResponse 형태로 반환되는 객체를 사용해야 합니다.

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        Product product = Product.create(category, deliveryType, createRequest);
entity가 dto를 주입받아서 create하게 되면 entity는 dto에 의존이 됩니다.
더중요한 객체가 덜 중요한 객체에 의존하게 됩니다.
반대로 dto->entity 변환되는 순서로 변경해보는건 어떨까요?

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/productTag/repository/impl/ProductTagRepositoryImpl.java
> +                .innerJoin(productTag.tag, tag)
.innerJoin(productTag.tag) 변경해보는건 어떨까요? 연관관계가 설정되어 있다면
  tag를 명시해 주지 않아도 됩니다.

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/util/FileUploadUtil.java
> +    private static final String UPLOAD_BASE_URL = "src/main/resources";
UPLOAD_BASE_URL properties로 빼주는게 좋을거 같내요. 
 profile에 따라서 경로를 변경해주세요. 서버환경에서의 경로와 , 로컬 환경에서의 경로를 분리해주세요.

2022-07-25 03:29 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipshoppingmall/util/FileUploadUtil.java
> +        return UUID.randomUUID().toString().replace("-", "") + fileExtension;
파일은 저장될 때 uuid로 파일명을 만들어서 저장을 하는거 같아요. 
한 폴더에 모두 등록되는 구조 같은데.. 파일스스템이라서. 한 폴더에 너무 많은 파일이 존재하면.. 성능 이슈가 발생할 수 있어요. 
폴더 형태를 /yyyy/mmdd/파일 or /yyyy/mm파일 ... 등등등 적절한 파일경로 저장 규칙을 만들어서 처리해보는건 어떨까요?

2022-07-25 04:06 UTC, HoFe-U commented on src/main/java/shop/gaship/gashipshoppingmall/product/repository/impl/ProductRepositoryImpl.java
> +        QCategory upper = new QCategory("upper");
상단에 이미 QCategroy.qCategory 를 사용하고 있어 상위카테고리를 조회하기 위해 새로 new 를 했습니다!

2022-07-25 04:26 UTC, HoFe-U commented on src/main/java/shop/gaship/gashipshoppingmall/product/service/impl/ProductServiceImpl.java
> +        Page<ProductAllInfoResponseDto> products = repository.findProduct(requestDto);
ProductRequestDto 가 모든조건에 대한 값을 다 가지고있기때문에 변경해서 전달했습니다.

2022-07-26 02:17 UTC, merged